//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.17 at 09:54:26 AM CEST 
//


package womo.spec;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Assurance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Assurance">
 *   &lt;complexContent>
 *     &lt;extension base="{}Requirement">
 *       &lt;sequence>
 *         &lt;element name="leftRecord" type="{}Record"/>
 *         &lt;element name="operator" type="{}Operator"/>
 *         &lt;element name="rightRecord" type="{}Record"/>
 *         &lt;element name="actions" type="{}Action" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Assurance", propOrder = {
    "leftRecord",
    "operator",
    "rightRecord",
    "actions"
})
public class Assurance
    extends Requirement
{

    @XmlElement(required = true)
    protected Record leftRecord;
    @XmlElement(required = true)
    protected Operator operator;
    @XmlElement(required = true)
    protected Record rightRecord;
    protected List<Action> actions;

    /**
     * Gets the value of the leftRecord property.
     * 
     * @return
     *     possible object is
     *     {@link Record }
     *     
     */
    public Record getLeftRecord() {
        return leftRecord;
    }

    /**
     * Sets the value of the leftRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link Record }
     *     
     */
    public void setLeftRecord(Record value) {
        this.leftRecord = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link Operator }
     *     
     */
    public Operator getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Operator }
     *     
     */
    public void setOperator(Operator value) {
        this.operator = value;
    }

    /**
     * Gets the value of the rightRecord property.
     * 
     * @return
     *     possible object is
     *     {@link Record }
     *     
     */
    public Record getRightRecord() {
        return rightRecord;
    }

    /**
     * Sets the value of the rightRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link Record }
     *     
     */
    public void setRightRecord(Record value) {
        this.rightRecord = value;
    }

    /**
     * Gets the value of the actions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Action }
     * 
     * 
     */
    public List<Action> getActions() {
        if (actions == null) {
            actions = new ArrayList<Action>();
        }
        return this.actions;
    }

}
