//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.22 at 11:30:57 PM CEST 
//


package womo.evt;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for EvtType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EvtType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="formular"/>
 *     &lt;enumeration value="time"/>
 *     &lt;enumeration value="counter"/>
 *     &lt;enumeration value="assurance"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum EvtType {

    @XmlEnumValue("formular")
    FORMULAR("formular"),
    @XmlEnumValue("time")
    TIME("time"),
    @XmlEnumValue("counter")
    COUNTER("counter"),
    @XmlEnumValue("assurance")
    ASSURANCE("assurance");
    private final String value;

    EvtType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EvtType fromValue(String v) {
        for (EvtType c: EvtType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
